rule-providers: 
  download:           {type: file, behavior: classical, format: yaml, path: /root/.config/mihomo/rules/download.yaml}
  fix-direct:         {type: file, behavior: classical, format: yaml, path: /root/.config/mihomo/rules/fix-direct.yaml}
  XPTV:               {type: file, behavior: classical, format: yaml, path: /root/.config/mihomo/rules/XPTV.yaml}
  telegram:           {type: file, behavior: domain, format: mrs, path: /root/.config/mihomo/rules/telegram.mrs}
  category-ai-!cn:    {type: file, behavior: domain, format: mrs, path: /root/.config/mihomo/rules/category-ai-!cn.mrs}
  geolocation-!cn:    {type: file, behavior: domain, format: mrs, path: /root/.config/mihomo/rules/geolocation-!cn.mrs}
  youtube:            {type: file, behavior: domain, format: mrs, path: /root/.config/mihomo/rules/youtube.mrs}
  spotify:            {type: file, behavior: domain, format: mrs, path: /root/.config/mihomo/rules/spotify.mrs}
  netflix:            {type: file, behavior: domain, format: mrs, path: /root/.config/mihomo/rules/netflix.mrs}
  disney:             {type: file, behavior: domain, format: mrs, path: /root/.config/mihomo/rules/disney.mrs}
  hbo:                {type: file, behavior: domain, format: mrs, path: /root/.config/mihomo/rules/hbo.mrs}
  connectivity-check: {type: file, behavior: domain, format: mrs, path: /root/.config/mihomo/rules/connectivity-check.mrs}
  private_domain:     {type: file, behavior: domain, format: mrs, path: /root/.config/mihomo/rules/private.mrs}
  cn_domain:          {type: file, behavior: domain, format: mrs, path: /root/.config/mihomo/rules/cn.mrs}
  apple-cn:           {type: file, behavior: domain, format: mrs, path: /root/.config/mihomo/rules/apple-cn.mrs}
  cn_ip:              {type: file, behavior: ipcidr, format: mrs, path: /root/.config/mihomo/rules/cn_ip.mrs}
  private_ip:         {type: file, behavior: ipcidr, format: mrs, path: /root/.config/mihomo/rules/private_ip.mrs}
